package com.lukeneedham.flowerpotrecycler.autoadapter

import android.content.Context
import com.lukeneedham.flowerpotrecycler.autoadapter.builderbinder.BuilderBinder
import com.lukeneedham.flowerpotrecycler.delegatedadapter.DelegatedRecyclerAdapter
import com.lukeneedham.flowerpotrecycler.delegatedadapter.config.RecyclerAdapterConfig

class AutoGeneratedRecyclerAdapter<ItemType>(
    private val builderBinder: BuilderBinder<ItemType>,
    config: RecyclerAdapterConfig<ItemType, AutoGeneratedRecyclerItemView<ItemType>>
) : DelegatedRecyclerAdapter<ItemType, AutoGeneratedRecyclerItemView<ItemType>>(config) {
    override fun createItemView(context: Context) =
        AutoGeneratedRecyclerItemView(context, builderBinder)
}