package com.lukeneedham.flowerpotrecycler.autoadapter

import android.annotation.SuppressLint
import android.content.Context
import android.view.View
import android.widget.FrameLayout
import com.lukeneedham.flowerpotrecycler.autoadapter.builderbinder.BuilderBinder
import com.lukeneedham.flowerpotrecycler.simpleadapter.SimpleRecyclerItemView

@SuppressLint("ViewConstructor")
internal class AutoGeneratedRecyclerItemView<ItemType>(
    context: Context,
    private val builderBinder: BuilderBinder<ItemType>
) :
    FrameLayout(context), SimpleRecyclerItemView<ItemType> {

    init {
        addView(builderBinder.build(this))
    }

    override fun setItem(item: ItemType, itemView: View) {
        builderBinder.bind(item, this)
    }
}