package com.lukeneedham.flowerpotrecycler.autoadapter

import com.lukeneedham.flowerpotrecycler.autoadapter.builderbinder.BuilderBinder
import com.lukeneedham.flowerpotrecycler.delegatedadapter.config.RecyclerAdapterConfig
import com.lukeneedham.flowerpotrecycler.delegatedadapter.singletype.ConfigurableSingleTypeRecyclerAdapter
import kotlin.reflect.KClass

object AutoGeneratedRecyclerAdapterBuilder {
    inline fun <reified ItemType : Any> build(
        builderBinder: BuilderBinder<ItemType>,
        config: RecyclerAdapterConfig<ItemType>?
    ) = ConfigurableSingleTypeRecyclerAdapter(
        ItemType::class,
        // TODO: Does this even work?
        AutoGeneratedRecyclerItemView::class as KClass<AutoGeneratedRecyclerItemView<ItemType>>,
        config
    ) {
        AutoGeneratedRecyclerItemView(it, builderBinder)
    }
}
