package com.lukeneedham.flowerpotrecycler.autoadapter

import com.lukeneedham.flowerpotrecycler.autoadapter.builderbinder.BuilderBinder
import com.lukeneedham.flowerpotrecycler.delegatedadapter.config.RecyclerAdapterConfig
import com.lukeneedham.flowerpotrecycler.delegatedadapter.singletype.ConfigurableSingleTypeRecyclerAdapter

object AutoGeneratedRecyclerAdapterBuilder {
    inline fun <reified ItemType : Any> build(
        builderBinder: BuilderBinder<ItemType>,
        config: RecyclerAdapterConfig<ItemType>?
    ) = ConfigurableSingleTypeRecyclerAdapter(ItemType::class, config) {
        AutoGeneratedRecyclerItemView(it, builderBinder)
    }
}
