package com.lukeneedham.flowerpotrecycler.autoadapter

import android.content.Context
import com.lukeneedham.flowerpotrecycler.autoadapter.builderbinder.BuilderBinder
import com.lukeneedham.flowerpotrecycler.simpleadapter.SimpleRecyclerAdapter

internal class AutoGeneratedRecyclerAdapter<ItemType>(
    items: List<ItemType>,
    private val builderBinder: BuilderBinder<ItemType>
) : SimpleRecyclerAdapter<ItemType, AutoGeneratedRecyclerItemView<ItemType>>(items) {
    override fun createItemView(context: Context) =
        AutoGeneratedRecyclerItemView(
            context,
            builderBinder
        )
}