package com.lukeneedham.flowerpotrecycler

import android.content.Context
import android.view.View
import android.view.ViewGroup
import androidx.annotation.LayoutRes
import com.lukeneedham.flowerpotrecycler.autoadapter.AutoGeneratedRecyclerAdapterBuilder
import com.lukeneedham.flowerpotrecycler.autoadapter.AutoGeneratedRecyclerItemView
import com.lukeneedham.flowerpotrecycler.autoadapter.builderbinder.XMLBuilderBinder
import com.lukeneedham.flowerpotrecycler.autoadapter.builderbinder.declarative.DeclarativeBindingDsl
import com.lukeneedham.flowerpotrecycler.autoadapter.builderbinder.declarative.DeclarativeBuilderBinder
import com.lukeneedham.flowerpotrecycler.delegatedadapter.RecyclerItemView
import com.lukeneedham.flowerpotrecycler.delegatedadapter.config.RecyclerAdapterConfig
import com.lukeneedham.flowerpotrecycler.delegatedadapter.multitype.*
import com.lukeneedham.flowerpotrecycler.delegatedadapter.singletype.ConfigurableSingleTypeRecyclerAdapter
import com.lukeneedham.flowerpotrecycler.delegatedadapter.singletype.SingleTypeRecyclerAdapter
import com.lukeneedham.flowerpotrecycler.staticviewadapter.StaticViewRecyclerAdapter
import com.lukeneedham.flowerpotrecycler.staticviewadapter.config.StaticViewRecyclerAdapterConfig

@Suppress("unused")
object RecyclerAdapterBuilder {

    /**
     * Auto-generate an adapter.
     * To be used when creating the item View programmatically (for example, with Anko DSL Layouts)
     *
     * Use [onItem][com.lukeneedham.flowerpotrecycler.autoadapter.builderbinder.declarative.DeclarativeBindingDsl.onItem]
     * within your builder to update the UI when an item is bound.
     * @param builder The callback for building item Views
     * @param config Optional configuration for the adapter
     */
    inline fun <reified ItemType : Any> fromDeclarativeDsl(
        config: RecyclerAdapterConfig<ItemType>? = null,
        noinline builder: DeclarativeBindingDsl<ItemType>.(ViewGroup) -> View
    ): SingleTypeRecyclerAdapter<ItemType, AutoGeneratedRecyclerItemView<ItemType>> {
        val builderBinder = object : DeclarativeBuilderBinder<ItemType>() {
            override val builder = builder
        }
        return AutoGeneratedRecyclerAdapterBuilder.build(builderBinder, config)
    }

    /**
     * Auto-generate an adapter.
     * To be used when creating the item View from inflating an XML layout.
     * @param layoutResId The XML layout resource ID to inflate to build the View
     * @param binder The callback for binding each item to its View
     * @param config Optional configuration for the adapter
     */
    inline fun <reified ItemType : Any> fromXml(
        @LayoutRes layoutResId: Int,
        config: RecyclerAdapterConfig<ItemType>? = null,
        noinline binder: (Int, ItemType, View) -> Unit
    ): SingleTypeRecyclerAdapter<ItemType, AutoGeneratedRecyclerItemView<ItemType>> {
        val builderBinder = object : XMLBuilderBinder<ItemType>(layoutResId) {
            override fun bind(position: Int, item: ItemType, itemView: View) {
                binder(position, item, itemView)
            }
        }
        return AutoGeneratedRecyclerAdapterBuilder.build(builderBinder, config)
    }

    /* From Multi Type */

    fun fromTypeRegistry(
        viewTypesRegistry: ViewTypesRegistry<Any, View>,
        config: RecyclerAdapterConfig<Any>? = null
    ): MultiTypeRecyclerAdapter<Any, View, TypedViewHolder<View>> =
        ConfigurableMultiTypeRecyclerAdapter(viewTypesRegistry, config)

    /* From Single Type */

    /**
     * Setup without writing an adapter.
     * To be used when View logic is contained within its own class, and you want to instantiate the View object yourself.
     * @param createView The function to instantiate your [ItemViewType] class
     * @param config Configuration for the adapter
     */
    inline fun <reified ItemType : Any, ItemViewType> fromViewCreator(
        config: RecyclerAdapterConfig<ItemType>? = null,
        noinline createView: (Context) -> ItemViewType
    ): SingleTypeRecyclerAdapter<ItemType, ItemViewType>
            where ItemViewType : View, ItemViewType : RecyclerItemView<ItemType> =
        ConfigurableSingleTypeRecyclerAdapter(config, createView)

    /**
     * Setup without writing an adapter.
     * To be used when View logic is contained within its own class.
     *
     * The type parameter 'ItemViewType' is the type of the View class, which will handle binding items.
     * This class is automatically instantiated using its View(Context) constructor.
     *
     * @param config Configuration for the adapter
     */
    inline fun <reified ItemType : Any, reified ItemViewType> fromView(
        config: RecyclerAdapterConfig<ItemType>? = null
    ): SingleTypeRecyclerAdapter<ItemType, ItemViewType>
            where ItemViewType : View, ItemViewType : RecyclerItemView<ItemType> =
        fromViewClass(ItemViewType::class.java, config)

    /**
     * Setup without writing an adapter.
     * To be used when View logic is contained within its own class.
     * @param itemViewClass The [ItemViewType] class which will handle binding items.
     * This class is automatically instantiated using its View(context: Context) constructor.
     * @param config Configuration for the adapter
     */
    @JvmStatic
    inline fun <reified ItemType : Any, ItemViewType> fromViewClass(
        itemViewClass: Class<ItemViewType>,
        config: RecyclerAdapterConfig<ItemType>? = null
    ): SingleTypeRecyclerAdapter<ItemType, ItemViewType>
            where ItemViewType : View, ItemViewType : RecyclerItemView<ItemType> =
        ConfigurableSingleTypeRecyclerAdapter(config) {
            itemViewClass.getConstructor(Context::class.java).newInstance(it)
        }

    /* From Static View */

    /**
     * A simple adapter wrapper around a static view.
     * Since the view is static, no binding is required, and no items need to be provided.
     * The adapter will always show the view a single time.
     *
     * To be used when View logic is contained within its own class, and you want to instantiate the View object yourself.
     * @param config Configuration for the adapter
     * @param createView The function to instantiate your [ViewType] class
     */
    fun <ViewType : View> fromStaticViewCreator(
        config: StaticViewRecyclerAdapterConfig? = null,
        createView: (Context) -> ViewType
    ): StaticViewRecyclerAdapter =
        StaticViewRecyclerAdapter(config, createView)

    /**
     * A simple adapter wrapper around a static view.
     * Since the view is static, no binding is required, and no items need to be provided.
     * The adapter will always show the view a single time.
     *
     * To be used when View logic is contained within its own class.
     * The type parameter [ViewType] is the type of the View class.
     * This class is automatically instantiated using its View(Context) constructor.
     * @param config Configuration for the adapter
     */
    inline fun <reified ViewType : View> fromStaticView(
        config: StaticViewRecyclerAdapterConfig? = null
    ): StaticViewRecyclerAdapter =
        fromStaticViewClass(ViewType::class.java, config)

    /**
     * A simple adapter wrapper around a static view.
     * Since the view is static, no binding is required, and no items need to be provided.
     * The adapter will always show the view a single time.
     *
     * To be used when View logic is contained within its own class.
     * @param viewClass The [ViewType] class which will handle binding items.
     * This class is automatically instantiated using its View(context: Context) constructor.
     * @param config Configuration for the adapter
     */
    @JvmStatic
    fun <ViewType : View> fromStaticViewClass(
        viewClass: Class<ViewType>,
        config: StaticViewRecyclerAdapterConfig? = null
    ): StaticViewRecyclerAdapter =
        StaticViewRecyclerAdapter(config) {
            viewClass.getConstructor(Context::class.java).newInstance(it)
        }
}
