package com.lukeneedham.flowerpotrecycler

import android.content.Context
import android.view.View
import android.view.ViewGroup
import androidx.annotation.LayoutRes
import androidx.recyclerview.widget.RecyclerView
import com.lukeneedham.flowerpotrecycler.autoadapter.AutoGeneratedRecyclerAdapter
import com.lukeneedham.flowerpotrecycler.autoadapter.builderbinder.XMLBuilderBinder
import com.lukeneedham.flowerpotrecycler.autoadapter.builderbinder.declarative.DeclarativeBindingDsl
import com.lukeneedham.flowerpotrecycler.autoadapter.builderbinder.declarative.DeclarativeBuilderBinder
import com.lukeneedham.flowerpotrecycler.simpleadapter.SimpleRecyclerAdapter
import com.lukeneedham.flowerpotrecycler.simpleadapter.SimpleRecyclerItemView

object RecyclerAdapterBuilder {

    /**
     * Auto-generate an adapter.
     * To be used when creating the item View programmatically (for example, with Anko DSL Layouts)
     *
     * Use [onItem][com.lukeneedham.flowerpotrecycler.autoadapter.builderbinder.declarative.DeclarativeBindingDsl.onItem]
     * within your builder to update the UI when an item is bound.
     * @param items The initial data to be shown in the [RecyclerView]
     * @param builder The callback for building item Views
     */
    fun <ItemType> fromDeclarativeDsl(
        items: List<ItemType>,
        builder: DeclarativeBindingDsl<ItemType>.(ViewGroup) -> View
    ): AutoGeneratedRecyclerAdapter<ItemType> {
        val builderBinder = object : DeclarativeBuilderBinder<ItemType>() {
            override val builder = builder
        }
        return AutoGeneratedRecyclerAdapter(items, builderBinder)
    }

    /**
     * Auto-generate an adapter.
     * To be used when creating the item View from inflating an XML layout.
     * @param items The initial data to be shown in the [RecyclerView]
     * @param layoutResId The XML layout resource ID to inflate to build the View
     * @param binder The callback for binding each item to its View
     */
    fun <ItemType> fromXml(
        items: List<ItemType>,
        @LayoutRes layoutResId: Int,
        binder: (Int, ItemType, View) -> Unit
    ): AutoGeneratedRecyclerAdapter<ItemType> {
        val builderBinder = object : XMLBuilderBinder<ItemType>(layoutResId) {
            override fun bind(position: Int, item: ItemType, itemView: View) {
                binder(position, item, itemView)
            }
        }
        return AutoGeneratedRecyclerAdapter(items, builderBinder)
    }

    /**
     * Setup without writing an adapter.
     * To be used when View logic is contained within its own class, and you want to instantiate the View object yourself.
     * @param items The initial data to be shown in the [RecyclerView]
     * @param createView The function to instantiate your [ItemViewType] class
     */
    fun <ItemType, ItemViewType> fromView(
        items: List<ItemType>,
        createView: (Context) -> ItemViewType
    )
            where ItemViewType : View, ItemViewType : SimpleRecyclerItemView<ItemType> =
        object : SimpleRecyclerAdapter<ItemType, ItemViewType>(items) {
            override fun createItemView(context: Context) = createView(context)
        }

    /**
     * Setup without writing an adapter.
     * To be used when View logic is contained within its own class, and you want to instantiate the View object yourself.
     * @param createView The function to instantiate your View class
     */
    fun <ItemType, ItemViewType> fromView(createView: (Context) -> ItemViewType)
            where ItemViewType : View, ItemViewType : SimpleRecyclerItemView<ItemType> =
        fromView(emptyList(), createView)

    /**
     * Setup without writing an adapter.
     * To be used when View logic is contained within its own class.
     *
     * The type parameter 'ItemViewType' is the type of the View class, which will handle binding items.
     * This class is automatically instantiated using its View(Context) constructor.
     *
     * @param items The initial data to be shown in the [RecyclerView]
     */
    inline fun <ItemType, reified ItemViewType> fromView(items: List<ItemType>)
            where ItemViewType : View, ItemViewType : SimpleRecyclerItemView<ItemType> =
        fromView(items, ItemViewType::class.java)

    /**
     * Setup without writing an adapter.
     * To be used when View logic is contained within its own class.
     *
     * The type parameter 'ItemViewType' is the type of the View class, which will handle binding items.
     * This class is automatically instantiated using its View(Context) constructor.
     */
    inline fun <ItemType, reified ItemViewType> fromView()
            where ItemViewType : View, ItemViewType : SimpleRecyclerItemView<ItemType> =
        fromView(emptyList(), ItemViewType::class.java)

    /**
     * Setup without writing an adapter.
     * To be used when View logic is contained within its own class.
     * @param items The initial data to be shown in the [RecyclerView]
     * @param itemViewClass The [ItemViewType] class which will handle binding items.
     * This class is automatically instantiated using its View(context: Context) constructor.
     */
    @JvmStatic
    fun <ItemType, ItemViewType> fromView(
        items: List<ItemType>,
        itemViewClass: Class<ItemViewType>
    )
            where ItemViewType : View, ItemViewType : SimpleRecyclerItemView<ItemType> =
        object : SimpleRecyclerAdapter<ItemType, ItemViewType>(items) {
            override fun createItemView(context: Context) =
                itemViewClass.getConstructor(Context::class.java).newInstance(context)
        }
}